### ISSUE TITLE
moves are being approven only when no capital letters

### ISSUE THREAD

**Issue by ekfoD** [MariusCes/Chess-exerciser-900#8]
it can be solved via back or front

**Comment by Jusatas** [comment]
Fixed by adding toLowerCase() in postMove 
`  const postMove = async (userMove) => {
    const response = await fetch(
      "http://localhost:5030/api/chess/" + gameID + "/move",
      {
        method: "POST",
        body: JSON.stringify({
          move: userMove.toLowerCase(),
        }),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      }
    );`
